version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      # changed host port to 27018 to avoid conflicts if 27017 is already in use
      - 27018:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/wedproject
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM=${TWILIO_FROM}
      - NODE_ENV=${NODE_ENV:-development}
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=hagiga
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_FORCE_PATH_STYLE=1
    depends_on:
      - mongo
      - minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data
volumes:
  mongo-data:
  minio-data:
